[package]
name = "async-openweather-rs"
version = "0.1.0"
edition = "2018"
authors = ["Mikhail Ruzavin <misharuz25@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
